name: Build and deploy Node.js app to Azure Web App - transfer-jpcatholic-node

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: npm install, build, and test
      run: |
        using: 'docker'
        image: 'Dockerfile't

    - name: 'Deploy to Azure Web App'
      uses: azure/webapps-deploy@v1
      with:
        app-name: 'transfer-jpcatholic-node'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_ba033a7f7a8c4154beaa6bacae656180 }}
        package: .
