name: Build and deploy Node.js app to Azure Web App - transfer-jpcatholic-node

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Build docker image
      run: docker build
